### PR TITLE
find queue elements by payload values

### PR DESCRIPTION
**Pull request by thestick613**
this is my first pull request on github ever, so .. shoot away.

### CODE REVIEW

**Comment by ktaragorn** [comment]
This is my first time receiving a PR too!
The code that is generating the query is looking repetitive, could you take a pass at DRYing that up? All that is different in the 2 blocks is the time query, and that could be an argument to a function that returns the query.
Just for my curiosity's sake, could you briefly tell me how you would use a feature like this?

**Comment by thestick613** [comment]
on master.py

```
queue.put({"type":"work", "masterid":"master_100","task":[2,2,3]}
sleep(5000)
print queue.get({"type":"work_result", "for_master":"master_100})
```

on worker.py

```
work = queue.get({"type":"work"})
if work:
    result = sum(work.payload["task"])
    queue.put({"type":"work_result", "for_master": work.payload["masterid"], "result": result})
```

The code that is generating the query is very basic, and it supports a limited syntax. I will try to freshen it up.

**Comment by ktaragorn** [comment]
So, as for the motivation, why this way instead of making seperate queues?

**Comment by thestick613** [comment]
I have a lot of masters and a lot of workers. The workers don't know the names of the masters when they go alive so they don't know where to connect.

**Comment by thestick613** [comment]
I've updated the code, and changed the logic a bit. Mongodb helps us with the query engine, so no need to reinvent the wheel.

**Pull request merged**
